# docker-compose.yml
version: '3.8'

services:
  kalender:
    build: .
    ports:
      - "3306:3306"
      - "4000:4000"
      - "8081:8081"
      - "3000:3000"
      - "8080:8080"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: