version: "3.8"

services:
  app:
    build: .
    image: "ghcr.io/scholet183/kalender:workflow_container_deployment"
    container_name: meine-app
    stdin_open: true  # Hält den Container offen
    tty: true
    ports:
      - "4200:4200"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - user-db
      - kalender-db
    networks:
      - app-network

  user-db:
    image: mariadb:latest
    container_name: user-datenbank
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=verysecret
      - MARIADB_DATABASE=userdatabase
      - MARIADB_USER=root
      - MARIADB_PASSWORD=verysecret
    ports:
      - "3307:3306"  # User-Datenbank läuft auf Port 3307
    volumes:
      - userdb-data:/var/lib/mysql
    networks:
      - app-network

  kalender-db:
    image: mariadb:latest
    container_name: kalender-datenbank
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=verysecret
      - MARIADB_DATABASE=calendardatabase
      - MARIADB_USER=root
      - MARIADB_PASSWORD=verysecret
    ports:
      - "3308:3306"  # Kalender-Datenbank läuft auf Port 3308
    volumes:
      - kalenderdb-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  userdb-data:
  kalenderdb-data:

networks:
  app-network:
