version: "3.8"

services:
  app:
    build: .
    container_name: meine-app
    stdin_open: true  # Hält den Container offen
    tty: true
    ports:
      - "4200:4200"
    depends_on:
      - user-ms
      - calendar-ms
    networks:
      - app-network

  user-ms:
    build: Website/user_microservice/
    stdin_open: true  # Hält den Container offen
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - user-db
    networks:
      - app-network

  calendar-ms:
    build: Website/calendar_microservice/
    stdin_open: true  # Hält den Container offen
    tty: true
    ports:
      - "8081:8081"
    depends_on:
      - calendar-db
    networks:
      - app-network


  user-db:
    image: mariadb:latest
    container_name: user-datenbank
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=verysecret
      - MARIADB_DATABASE=userdatabase
      - MARIADB_USER=root
      - MARIADB_PASSWORD=verysecret
    ports:
      - "3307:3306"  # User-Datenbank läuft auf Port 3307
    volumes:
      - userdb-data:/var/lib/mysql
    networks:
      - app-network

  calendar-db:
    image: mariadb:latest
    container_name: calendar-datenbank
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=verysecret
      - MARIADB_DATABASE=calendardatabase
      - MARIADB_USER=root
      - MARIADB_PASSWORD=verysecret
    ports:
      - "3308:3306"  # calendar-Datenbank läuft auf Port 3308
    volumes:
      - calendardb-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  userdb-data:
  calendardb-data:

networks:
  app-network:
