version: "3.8"

services:
  app:
    image: "ghcr.io/scholet183/kalender/app:latest"
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: meine-app
    ports:
      - "4200:4200"
    depends_on:
      - user-ms
      - calendar-ms
    networks:
      - app-network

  user-ms:
    image: "ghcr.io/scholet183/kalender/user:latest"
    build: 
      context: Website/user_microservice/
      dockerfile: Dockerfile
      target: prod
    container_name: user-microservice
    ports:
      - "8080:8080"
    depends_on:
      - user-db
    networks:
      - app-network

  user-ms-test:
    build: 
      context: Website/user_microservice/
      dockerfile: Dockerfile
      target: test
    ports:
      - "8080:8080"
    depends_on:
      - user-db
    networks:
      - app-network
    profiles:
      - test

  calendar-ms:
    image: "ghcr.io/scholet183/kalender/calendar:latest"
    build: 
      context: Website/calendar_microservice/
      dockerfile: Dockerfile
      target: prod
    container_name: calendar-microservice
    ports:
      - "8081:8081"
    depends_on:
      - calendar-db
    networks:
      - app-network

  calendar-ms-test:
    build: 
      context: Website/calendar_microservice/
      dockerfile: Dockerfile
      target: test
    ports:
      - "8081:8081"
    depends_on:
      - calendar-db
    networks:
      - app-network
    profiles:
      - test

  user-db:
    image: mariadb:latest
    container_name: user-datenbank
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_USER_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - "3307:3306"  # User-Datenbank läuft auf Port 3307
    volumes:
      - userdb-data:/var/lib/mysql
    networks:
      - app-network

  calendar-db:
    image: mariadb:latest
    container_name: calendar-datenbank
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_CALENDAR_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - "3308:3306"  # calendar-Datenbank läuft auf Port 3308
    volumes:
      - calendardb-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  userdb-data:
  calendardb-data:

networks:
  app-network:
