name: deploy_container
on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: prepare runner
        run: |
          sudo apt-get install docker-compose
      - name: build container
        run: |
          docker-compose build 
          docker-compose up -d
          docker images
          docker container ls
