name: test application
on: push

jobs:
  build-and-test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - name: prepare runner
        run: |
          sudo apt-get update 
          sudo apt-get install docker-compose
      - name: test calendar-ms
        run: docker-compose up calendar-ms-test
      - name: test user-ms
        run: docker-compose up user-ms-test
      - name: call deploy workflow
        uses: ./.github/workflows/deploy_container.yaml
